### ISSUE TITLE
return Distillery to chain more animations

### ISSUE THREAD

**Issue by thanhn08** [RamonGilabert/Morgan#3]
Hello there,

This is a great work! Thank you for building this and Walker.

I just have a suggestion that the methods in Morgan should return Distillery instead of receiving a completion block. This way, people can chain more animations or even chain the finally themselves into your built-in animation. For example, I may want to shake the button the hide it. Does it make sense?

As an example, instead of your shake method in Morgan+UIView, this is my version of shake that I am using with Walker in my app:

```
    public func shake(landscape: Bool = true, duration: NSTimeInterval = 0.075) -> Distillery {
        let x: CGFloat = landscape ? 25 : 0
        let y: CGFloat = landscape ? 0 : 25

        return animate(self, duration: duration) {
            $0.transform = CGAffineTransformMakeTranslation(-x, -y)
        }.chain(duration: duration) {
            $0.transform = CGAffineTransformMakeTranslation(x, y)
        }.chain(duration: duration) {
            $0.transform = CGAffineTransformMakeTranslation(-x / 2, -y / 2)
        }.chain(duration: duration) {
            $0.transform = CGAffineTransformIdentity
        }
    }
```

**Comment by RamonGilabert** [comment]
Hey @thanhn08 thank you for writing up!

I'm planning a small rewriting in the libraries to make them simpler to use, so I'll totally take this into account! :)

**Comment by thanhn08** [comment]
thank you!
